apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: production-
patchesStrategicMerge:
- patch-replicas.yaml
images:
- name: image-name
  newName: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/actionstest
  newTag: 23f82bc2e7ce06df01e0d85e703fcfbbdf740dbe
