apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prd
namePrefix: production-
patchesStrategicMerge:
- patch-replicas.yaml
- patch-buildconfig.yaml
- patch-is.yaml