kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nodejs
  namespace: apptest
  selfLink: /apis/build.openshift.io/v1/namespaces/apptest/buildconfigs/nodejs
  uid: 419f6b85-4d69-460b-aee8-d000f363d065
  resourceVersion: '200203'
  creationTimestamp: '2020-10-23T06:23:48Z'
  labels:
    app: nodejs
    app.kubernetes.io/component: nodejs
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/sclorg/nodejs-ex.git'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:10-SCL'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/sclorg/nodejs-ex.git'
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: nodejs-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: nodejs-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:94f29eed99e9053b916e50df94db3d1fa875f5307fa6bc19d5d516eb5e468d6f
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1