kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/sclorg/nodejs-ex.git'
  selfLink: /apis/image.openshift.io/v1/namespaces/apptest/imagestreams/nodejs
  resourceVersion: '200181'
  name: nodejs
  uid: 668abd4c-4aea-4a68-873e-920258524909
  creationTimestamp: '2020-10-23T06:23:47Z'
  generation: 1
  namespace: apptest
  labels:
    app: nodejs
    app.kubernetes.io/component: nodejs
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 'image-registry.openshift-image-registry.svc:5000/apptest/nodejs'