commonLabels:
  app: app-label
resources:
- deployment.yaml
- route.yaml
- imagestream.yaml
- buildconfig.yaml
- deploy2.yaml
configMapGenerator:
- name: testconfig
  literals:
  - aaa=bbb
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: image-name
  newName: 111/222/333
  newTag: "444"
