name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'imagename'
        required: true
        default: 'aaa/bbb:abcdef'

jobs:
  update_manifest:
    runs-on: ubuntu-latest
    env:
      IMAGE-NAME: ${{github.event.inputs.imagename}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: unkogero/pipelinetest
          ref: master
      - name: update
        run: |
          echo "${IMAGE-NAME}"
          echo "${{github.event.inputs.imagename}}"


          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          cd manifest/testapp/overlays/prd

          
          kustomize edit set image image-name=${{github.event.inputs.imagename}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3