name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'image-name'
        required: true
        default: 'aaa/bbb:abcdef'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: unkogero/pipelinetest
          ref: master
      - name: commit manifests
        run: |
          echo "${{ github.event.image-name }}"

          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          cd manifest/testapp/overlays/prd

          kustomize edit set image image-name=${{ github.event.image-name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3