name: merge

on:
  repository_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: unkogero/pipelinetest
          ref: master
      - name: post request
        run: |
          ls -lFR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
